### ISSUE TITLE
CUDA error detected: 700

### ISSUE THREAD

**Issue by weijing-tao** [tyhuang0428/DreamPhysics#1]
Thanks for the great work! However, I faced some errors when trying to run the demo with the data you provided.
Loading the existing point cloud  .ply file, an error is reported in mpm_solver.p2g2p below. It happens at random iteration, persistent even when i change the material type in config file, and for both ball and ficus object.
```
Error launching kernel: p2g_apic_with_stress on device cuda:0
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:958)
20%|█████████████████                                                               | 5/25 [00:05<00:20,  1.02s/it]
Traceback (most recent call last):
  File "/data/DreamPhysics-main/svd_simulation.py", line 361, in <module>
    mpm_solver.p2g2p(frame, substep_dt, device=device)
  File "/data/DreamPhysics-main/mpm_solver_warp/mpm_solver_warp.py", line 485, in p2g2p
    wp.launch(
  File "/data/anaconda3/envs/DreamPhysics/lib/python3.9/site-packages/warp/context.py", line 3220, in launch
    raise e
  File "/data/anaconda3/envs/DreamPhysics/lib/python3.9/site-packages/warp/context.py", line 3217, in launch
    runtime.verify_cuda_device(device)
  File "/data/anaconda3/envs/DreamPhysics/lib/python3.9/site-packages/warp/context.py", line 2422, in verify_cuda_device
    raise RuntimeError(f"CUDA error detected: {err}")
RuntimeError: CUDA error detected: 700
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223)
.
. (more lines of error line Warp CUDA error 700: an illegal memory access was encountered (/buildAgent/work/a9ae500d09a78409/warp/native/warp.cu:223) )
.
[E 05/08/24 08:17:52.218 62861] [cuda_driver.h:operator()(090)] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)
```

Thank you so much for your help!

**Comment by wkxNiubi** [comment]
Hi, I got the same error as you when reproducing the code. I would like to ask if you have solved it now.

**Comment by MontaEllis** [comment]
Same issue. How do you solve this?

**Comment by SMY19999** [comment]
When I run this on multi-GPU devices, I get this problem. After I run on 1 GPU, it is OK. My colleagues tell me that you can split `p2g2p` to `p2g` and `g2p` if you are familiar with MPM, it also works.
